name: Carson Howard's Developer Blog
description: Blogging about stuffs
meta_description: "Hey, blogging about stuff"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://cjhoward.dev"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Carson Howard"

# Disqus config
disqus-shortname: ""
