name: Maunder on about Software
description: A place for me to relay my thoughts data, design patterns, architecture, and all things software.

permalink: /:categories/:year/:month/:day/:title
markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://www.cjhoward.dev"
google_analytics: "UA-207366192-1"
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Details for the RSS feed generator
url: "https://www.cjhoward.dev"
author: "Carson Howard"

# Disqus config
disqus-shortname: ""

twitter:
  card: summary
  username: carson_howard

social:
  name: Carson Howard
  links:
    - https://twitter.com/carson_howard
    - https://www.linkedin.com/in/carson-howard-632b1752
    - https://github.com/cjhoward92
  
defaults:
  -
    scope:
      path: ""
    values:
      author: Carson Howard