name: Journey of a Dev
description: Blogging about data and software
meta_description: "Blogging about data and software - by Carson Howard"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://www.cjhoward.dev"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Carson Howard"

# Disqus config
disqus-shortname: ""
