name: Maunder on about Software
description: A place for me to blog about software architecture, patterns, and years of bad design
meta_description: |
  A reference for engineers to learn through years of trial and error.
  All the while picking through the ramblings of an old man.

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://www.cjhoward.dev"
google_analytics: "UA-XXXXXXXX-X"
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Details for the RSS feed generator
url: ""
author: "Carson Howard"

# Disqus config
disqus-shortname: ""

twitter:
  card: summary
  username: carson_howard

social:
  name: Carson Howard
  links:
    - https://twitter.com/carson_howard
    - https://www.linkedin.com/in/carson-howard-632b1752
    - https://github.com/cjhoward92
  
defaults:
  -
    scope:
      path: ""
    values:
      author: Carson Howard