name: Journey of a Dev
description: Blogging about data and software
meta_description: "Blogging about data and software - by Carson Howard"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://www.cjhoward.dev"
google_analytics: "UA-XXXXXXXX-X"
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Details for the RSS feed generator
url: ""
author: "Carson Howard"

# Disqus config
disqus-shortname: ""

twitter:
  card: summary
  username: carson_howard

social:
  name: Carson Howard
  links:
    - https://twitter.com/carson_howard
    - https://www.linkedin.com/in/carson-howard-632b1752
    - https://github.com/cjhoward92
  
defaults:
  -
    scope:
      path: ""
    values:
      author: Carson Howard